#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() //*!! Every Sensor Simple !!*//
{

while(1==1)
	  {            //*!! Every sensor should do something if it imediately starts when you run the code try tinkering with your hardware, and then tweek the code !!*//
	if(SensorValue(bumpSwitch) == 1 || SensorValue(limitSwitch) == 1 || SensorValue(lightSensor) >= 500 || SensorValue(sonar) >= 12 || SensorValue(lineFollower) >= 1500)
	  {
		startMotor(leftMotor, 127);
		startMotor(rightMotor, 127);            //*!! Should start every Motor/LED/Flashlight when one of the sensors are pressed !!*//
		startMotor(servoMotor, 127);
		turnFlashlightOn(flashlight, 100);
		turnLEDOn(green);
		startMotor(flashlight, 100);
	  }
	else
	  {
		stopMotor(leftMotor);
		stopMotor(rightMotor);
		stopMotor(servoMotor);
		turnFlashlightOff(flashlight);
		turnLEDOff(green);
		stopMotor(flashlight);
	  }
     }
}
