#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()                                      //*!! Motor Code !!*//
{

while(1==1){                                    //*!! 1==1 means always true. but you can just replace it with the word true!!*//
	if(SensorValue(bumpSwitch) == 1)
	{
		startMotor(servoMotor, 127);
	}
	else{
		stopMotor(servoMotor);
	}
	if(SensorValue(limitSwitch) == 1)
	{
		startMotor(rightMotor, 127);
		startMotor(leftMotor, 127);
	}
	else{
		stopMotor(rightMotor);
		stopMotor(leftMotor);
	}
}

}                                              //*!! bumpSwitch is the button, limitSwitch is the 3rd class lever. !!*//
